FROM python:3.9-slim

WORKDIR /app

COPY shared/requirements.txt /app/shared/requirements.txt
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r /app/shared/requirements.txt

COPY shared /app/shared
COPY video_analysis_worker.py /app/video_analysis_worker.py

CMD ["python", "video_analysis_worker.py"]
